name: NextJs build using Caching and Artifacts
on:
  push: 
    branches: [ main ]

jobs:
 NextJS-App:
    runs-on: ubuntu-latest
    concurrency: 
       group: deploy
       cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2.8.0
      - name: NodeJS with cache
        uses: Drafteame/node-cache-action@v0.3.0
        with:
          node-version: 24.x
          cache: npm
      - name: install dependencies
        run: npm install
      - name: Build NextJs
        run: npm run build
      - name: Download a Build Artifact 
        uses: actions/upload-artifact@v7.0.1
        with:
          # Artifact name
          name: Artifacts the build output which helps during the deployments
          # Destination path
          path: out/
